### ISSUE TITLE
Archive this feedstock

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/avrocpp-feedstock#20]
It seems this is building the same thing as https://github.com/conda-forge/avro-feedstock, and hasn't been touched in ages.

CC @conda-forge/avrocpp @conda-forge/avro @conda-forge/core

**Comment by nugend** [comment]
This appears to be the only conda forge package which installs the C++ library for avro. Rather than archiving it, it would be nice if it could be updated if possible.

**Comment by xhochy** [comment]
This needs a volunteer than that updates it. Otherwise, we should archive.

**Comment by jakirkham** [comment]
Maybe I'm missing it, but it looks

* `avro` is a pure Python package
* `avrocpp` is a C++ library

Was there something else here that I'm missing?

That said, completely agree this feedstock looks like it needs some attention

**Comment by nugend** [comment]
I’m going to try and spend a little time getting some updates done to this this weekend as I need this.

not sure if an update will close out the boost fix up issue since that seems to depend on the next minor release of avro since the 1.11 branch doesn’t fix deprecations (might have misread the commit history).

**Comment by jakirkham** [comment]
Thanks Daniel! 🙏

**Comment by nugend** [comment]
@h-vetinari @jakirkham I think I’ve got the build fixed up for Linux/OS X. Don’t have much experience with Windows dev though so I’m not sure how to fix those issues. Do either of you know if there are any guides or resources on Conda Windows build configurations that I could look at?

**Comment by jakirkham** [comment]
Thanks Daniel! 🙏

Are these fixes in a PR somewhere?

**Comment by nugend** [comment]
Yes, #21

**Comment by nugend** [comment]
I don't think I can get this done. 1) I have no idea how to replicate the linux build issue where CMake can't be pointed to the module for finding snappy and 2) I have absolutely no idea how to fix the Windows build issue with the missing integer types, I don't do Windows dev work, and I have little motivation to make it work because 3) Avro CPP turns out to *not* be useful to me because it doesn't support zstd. Someone else wants to fork and submit a new PR to fix the build, please, feel free.

**Comment by apmorton** [comment]
@h-vetinari @jakirkham I have a PR with a green build up to bump this package to the latest upstream and become a maintainer: https://github.com/conda-forge/avrocpp-feedstock/pull/25

**Comment by apmorton** [comment]
Closing as this feedstock should not be archived.

Potentially https://github.com/conda-forge/avro-feedstock could be converted to multi-output, but I'm happy to maintain this separately for the time being.

**Comment by h-vetinari** [comment]
Thanks for fixing it!
